### PR TITLE
Add possibility to include affixes in lambda functions, Issue #100, 2

### PR DESCRIPTION
**Pull request by nongenti**
Hallo @seboettg,

it is not possible to create a pull request with "Allow edits by maintainers", if owner is an organization.
[https://github.community/t/how-can-we-enable-allow-edits-from-maintainers-by-default/2847/6](https://github.community/t/how-can-we-enable-allow-edits-from-maintainers-by-default/2847/6)

My organization gave me permission to create a user-owned fork in this case.

I hope now all is right.

Regards,
Christian

### CODE REVIEW

**Comment by seboettg** [comment]
Hi @nongenti!
Now I'm able to add commits to your PR. Thank you for that and sorry that hassle. But now it's much easier to discuss your suggested changes and to work on it in a more collaborative way. 

I wrote a simple test case for the requirement of issue #100 and unfortunately your changes does not work as expected.
The setup of the test case is 

``` 
$additionalMarkup = [
    "title" => [
        'function' => function ($cslItem, $renderedText) {
            return '<span class="cite-title">' . $renderedText . '</span>';
        },
        'affixes' => false
    ],
    "citation-number" => [
        'function' => function ($cslItem, $renderedText) {
            return '<span class="cite-no">' . $renderedText . '</span>';
        },
        'affixes' => true
    ]
];
```
Stylesheet: `springer-lecture-notes-in-computer-science`. You can find the used CSL data in my commit. 
Anyhow, I would expect that the rendered result is like this:
```
  <div class="csl-entry"><div class="csl-left-margin"><span class="cite-no">1.</span></div><div class="csl-right-inline">Doe, J., III: <span class="cite-title">My Anonymous Heritage</span>. (2001).</div></div>
```
But the actual result is:
```
<div class="csl-entry"><div class="csl-left-margin"><span class="cite-no"><span class="cite-no">1</span>.</span></div><div class="csl-right-inline">Doe, J., III: <span class="cite-title">My Anonymous Heritage</span>. (2001).</div></div>\
``` 
The embracing span tag `<span class="cite-no">`, as defined in `$additionalMarkup`, appears two times nested in each other.

**Comment by seboettg** [comment]
Hi @nongenti, do you have any ideas to solve this?

**Comment by nongenti** [comment]
Hi @seboettg, sorry I've to finish an other project this week. I will look at this next week.

**Comment by nongenti** [comment]
Hi @seboettg,
is there any other problem with that?

**Pull request merged**
