### PR TITLE
create possibility to filter specific citations in "render" function, independently from CSL input data.

### PR DESCRIPTION
**Pull request by CarlosCraviotto**
Why do we need it? Cos when we are trying to render a citation and it is part of a number of bibliography but it's not the number 1 we will be able to send the field "citation-number" and render with it.

### CODE REVIEW

**Comment by seboettg** [comment]
Hi Carlos!
Thank you for your PR. I'm a bit confused. According to [csl-data schema](https://github.com/citation-style-language/schema/blob/master/csl-data.json#L293) there is a property `citation-number` but [this discussion](https://github.com/citation-style-language/test-suite/issues/1#issue-210075144) indicates that there isn't a property, and citation-number is just determined by the order in which the items are stored in the array.

Do you have any idea? And where do you get your CSL input data from? I haven't seen an example yet which using `citation-number` property.

**Comment by CarlosCraviotto** [comment]
Hi Sebastian, 
Thanks for your quick answer. 
My problem came up when I'm trying to render an individual citation and it's part of a bibliography list, in this case, a lot of standards (elsevier-vancouver) are using the citation-number as a reference to match the citation with The bibliography therefore I will need a property to declare it and the citation-number looks like a good choose.

**Comment by seboettg** [comment]
I'm not sure whether I understood the actual problem completely. 
In case of "Elsevier Vancouver" there are two possibilities:
1) the citation-number is a non-empty property of your input data: In this case, the value (i, 1..n) of the property will be used as reference as well in citation as in bibliography.
2) the citation-number doesn't exist: In this case the array key (j, 0..n) but increased by 1 will be used.
The result is the same, in both cases.

**Comment by seboettg** [comment]
I'm not sure if I understood the actual problem completely. 
In case of "Elsevier Vancouver" there are two possibilities:
1) the citation-number is a non-empty property of your input data: In this case, the value (i, 1..n) of the property will be used as reference as well in citation as in bibliography.
2) the citation-number doesn't exist: In this case, the array key (j, 0..n), will be used, but increased by 1.

In both cases the result is the same.

**Comment by CarlosCraviotto** [comment]
I will give you an example: 
I have this two bibliographies: 

_[1] World Health Organization. Drinking water [Internet]. Geneva: World Health Organization; 2015 Jun [cited 2015 Jul 20]. Available from: http://www.who.int/mediacentre/factsheets/fs391/en/_
_[2] Heart Foundation (AU). Dads and carers [Internet]. Deakin, ACT (Australia): Heart Foundation (AU); 2015 [cited 2015 Jun 30]. Available from: http://www.heartfoundation.org.au/healthy-eating/mums-united/about-mums-united/Pages/Dads-and-Carers.aspx_

And now I want to render as a citation just the _Heart Foundation (AU)_. As I'm using the vancouver style, the csl processor will return _[1]_ because when I'm rendering it I'm sending the data for this one and I don't have any way (I didn't find any) to tell to the processor this is the second one.
Thanks a lot for your time.

**Comment by seboettg** [comment]
Okay, I understand the problem. But I guess we need a different approach, which enables citeproc users to filter specific citations without changing the CSL input data. Another advantage for this way is also that we're closer to citeproc-js, the reference implementation of a CSL processor and I'm able to still use the test-suite.
I'll push a suggestion soon.

**Comment by seboettg** [comment]
This approach enables you to filter specific citation items by a filter array which you can pass to the render function while rendering citations. In that array are one or more stdClass objects containing an id property which references the item that should be rendered.
```php
$dataString = '[
            {
                "id": "ITEM-1",
                "title": "Book 1",
                "type": "book"
            },
            {
                "id": "ITEM-2",
                "title": "Book 2",
                "type": "book"
            },
            {
                "id": "ITEM-3",
                "title": "Book 3",
                "type": "book"
            }
        ]';
$data = json_decode($dataString);
$filter = json_decode('[{"id":"ITEM-3"}]');
$citeProc->render($data, "citation", $filter);
```

Another example you will find in [example/index.php](https://github.com/CarlosCraviotto/citeproc-php/blob/549f672635680a78a1f3ddb4a0e964d307ec724f/example/index.php).

What do you think?

**Comment by CarlosCraviotto** [comment]
Great!!! I like it 👍

**Pull request merged**
