### PR TITLE
Call to a member function getRangeDelimiter() on null

### PR DESCRIPTION
**Pull request by jonathangreen**
## Issue

I was seeing a fatal error while calling into this library from my code:
```
Error: Call to a member function getRangeDelimiter() on null in Seboettg\CiteProc\Rendering\Date\Date->render()
```

## Test cases

I have added two new test cases in this PR, both were failing previously:
[bugfix-github-dates-minimal.txt](https://github.com/seboettg/citeproc-php/pull/64/files#diff-b27da91c71df2aac6f24a49ba2fda1e2)
In this case the whole date was rendering, instead of just the datepart specified in the CSL.
```
--- Expected
+++ Actual
@@ @@
-'2004'
+'October 21–23, 2004'
```

[bugfix-github-dates.txt](https://github.com/seboettg/citeproc-php/pull/64/files#diff-0f759ac291f0d26a01e13dcab117efa8)
In this case I was getting a fatal error
```
Error: Call to a member function getRangeDelimiter() on null in Seboettg\CiteProc\Rendering\Date\Date->render()
```

## Fix

The fix here was two-fold, one was to ensure the part of the date range we are rendering is actually specified in the CSL, and the other is to fall back to normal date rendering if the part of the date required in the CSL is not actually part of the date range.

## Additional Notes:

Any feedback on this fix would be much appreciated, I would like to see it merged into the project as this case is causing issues for one of the users of my software that calls out to this library. Also thank you for building and maintaining this very useful library. 

## Interested parties

@seboettg

### CODE REVIEW

**Comment by seboettg** [comment]
Hi @jonathangreen
Great work! As far as I can see, it looks very good. I'll take a closer look soon. Since all tests  were passed successfully, I think I can merge your changes without running in other problems.
Thank you.

**Comment by seboettg** [comment]
@jonathangreen I did a little refactoring. If it's ok for you, I would merge the PR into master.

**Comment by jonathangreen** [comment]
Looks good to me!

**Comment by seboettg** [comment]
I still wait for an answer to another issue. But I will release in about a week.

**Comment by jonathangreen** [comment]
Thanks @seboettg appreciate the quick feedback / merge!

**Pull request merged**
