### PR TITLE
Add possibility to include affixes in lambda functions, Issue #100

### PR DESCRIPTION
**Pull request by nongenti**
A solution to include affixes in lambda funcitons. If you want to include affixes, change the $additionalMarkup array like this: 
```
$additionalMarkup = [
    'title' => array(
    	'function' => $titleFunction,
    	'affixes' => TRUE),
    'author' => array(
    	'function' => $authorFunction,
    	'affixes' => TRUE)
];
```
If you set `'affixes' => FALSE` or use the previous syntax, then it works as before.

### CODE REVIEW

**Comment by seboettg** [comment]
Hello @nongenti!
Thank you for this PR! I have some code additions I'd like to discuss in this PR, but for that I need PUSH access to the PR. You have to add priviliges for that. More information on https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork
Thank you!

**Comment by isgrim** [comment]
Hi @seboettg ,

I tried to change it. But could not find any setting, which applies to this.

**Comment by isgrim** [comment]
Yes, sadely the checkbox is not available.

**Comment by seboettg** [comment]
Hello @nongenti and @isgrim!

To summarize all necessary steps:

1. create a new branch in the forked repo containing your changes
2. create a new pull request and select the forked repo and the new branch as head
3. select the "seboettg/citeproc-php" and the master branch as base
4. select "Allow edits by maintainers"
5. add title and description for your PR
6. submit the pull request

Then, with the new PR I'm able to commit changes and it is much easier to discuss.

I'm going to close this PR now.

**Pull request closed without merging**
